### ISSUE TITLE
Unauthenticated error

### ISSUE THREAD

**Issue by bgmastermind** [intergo/laravel-smsto#3]
Is this ready for usage? 
I have put, correct data in .env file, but I get
```
array:2 [▼
  "success" => false
  "message" => "Unauthenticated."
]
```

**Comment by bgmastermind** [comment]
Found the issue. 
In vendor\intergo\smsto-php\src\Intergo\SmsTo\Http\Client.php 
$baseUrl default is wrong, and actual value in config is not being used at all.

**Comment by mannysoft** [comment]
Hi @bgmastermind,

Please take note that this package is not officially released.

You can change the source code to try it out anyway.

Thanks
