### ISSUE TITLE
Laravel 9 Support

### ISSUE THREAD

**Issue by igorkgg** [intergo/laravel-smsto#8]
Can you please add support for [Laravel 9](https://laravel.com/docs/9.x/upgrade)?

**Comment by poupouxios** [comment]
HI @igorkgg 

Thanks for the Pull Request. we will deploy it on one of our internal Laravel instances and run some tests and then we can merge it.

**Comment by poupouxios** [comment]
Running all tests
Testing Campaign List PASSED
Testing Message List PASSED
Testing Estimate single message PASSED
Testing Estimate campaign message PASSED
Testing Estimate personalized message PASSED
Testing Send single message PASSED
Testing Send campaign message PASSED
Testing Send personalized message PASSED
Testing Team Member List PASSED
Testing Team Invitation List PASSED
Testing Generate new member PASSED
Testing Invite new member PASSED
Testing Disable existing member PASSED
Testing Enable existing member PASSED
Testing Crediting existing member PASSED
Testing Debiting existing member PASSED
Testing Deleting existing member PASSED
Testing Contact List PASSED
Testing New Contact List PASSED
Testing New Contact in List PASSED
Testing All Contact in List PASSED
Testing Optin contact in List PASSED
Testing Optout contact in List PASSED
Testing Delete List PASSED
Testing Shortlink List PASSED
Testing New Shortlink PASSED
Testing Shortlink Report PASSED
Testing Delete Shortlink PASSED
Testing Numberlookup Estimate PASSED
Testing Numberlookup Verify PASSED
